### ISSUE TITLE
Error in require('live.io')

### ISSUE THREAD

**Issue by Danjavia** [akshaylive/live.io#7]
express-session deprecated req.secret; provide secret option node_modules\live.io\index.js:62:13
e:\virtualhost\simplyshare\app.js:24
app.use(express.static(path.join(__dirname, 'public')));
                      ^
TypeError: undefined is not a function
    at Object.<anonymous> (e:\virtualhost\simplyshare\app.js:24:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (e:\virtualhost\simplyshare\bin\www:7:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! simplyshare@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simplyshare@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the simplyshare package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls simplyshare
npm ERR! There is likely additional logging output above.

**Comment by akshaylive** [comment]
Can you provide how you are initializing live.io? 

Use this as an example - 
var app = live({
        sessionSecret: config.sessionSecret,
        store: sessionStore,
        cookieParser: cookieParser
    });

The sessionSecret cannot be empty. Please use a string non-empty value and let me know if it works. Thanks!

**Comment by akshaylive** [comment]
Closing issue due to inactivity
